global.nameBot = 'LuminaV2'
global.owner = ['62882006639544']
global.ownerName = 'Xena'
global.dev = "Xena"
global.prefix = '.'
global.version = '1.0.0'
global.footer = '© Created by Xena'
global.sessionName = 'session'
global.thumb = 'https://c.termai.cc/i129/y3Fx8T.jpg'
global.customPairing = 'LUMINAAA' // Custom pairing code, minimal 8 karakter
